// import 'package:hive_flutter/hive_flutter.dart';
// import 'package:path_provider/path_provider.dart';
// import 'package:yandex_shmr_hw/features/finance/data/entities/account/account_entity.dart';
// import 'package:yandex_shmr_hw/features/finance/data/entities/category/category_entity.dart';
// import 'package:yandex_shmr_hw/features/finance/data/entities/transaction/transaction_entity.dart';
// import 'package:yandex_shmr_hw/features/finance/data/models/enums/currency.dart'; // Import for Currency adapter

// class HiveService {
//   // Boxes
//   late Box<AccountEntity> accountsBox;
//   late Box<CategoryEntity> categoriesBox;
//   late Box<TransactionEntity> transactionsBox;

//   Future<void> init() async {
//     final appDocumentDir = await getApplicationDocumentsDirectory();
//     await Hive.initFlutter(appDocumentDir.path);

//     // Register all adapters generated by hive_generator
//     Hive.registerAdapter(AccountEntityAdapter());
//     Hive.registerAdapter(CategoryEntityAdapter());
//     Hive.registerAdapter(TransactionEntityAdapter());
//     Hive.registerAdapter(
//       CurrencyAdapter(),
//     ); // Register the Currency enum adapter

//     // Open boxes
//     accountsBox = await Hive.openBox<AccountEntity>('accounts');
//     categoriesBox = await Hive.openBox<CategoryEntity>('categories');
//     transactionsBox = await Hive.openBox<TransactionEntity>('transactions');
//   }

//   Future<void> clearAllData() async {
//     await accountsBox.clear();
//     await categoriesBox.clear();
//     await transactionsBox.clear();
//   }
// }
